name: mimik
api:
  name: mess
  controllerPath: ../src/controllers
  outputPath: ./build
  securityHandlerPath: ../src/securityHandlers
  swagger: node_modules/swagger-mess/mess-api-swagger.yml
  
package:
  imageName: mess
  imageIndexFilePath: ./build/index.js
  outputFolder: ./deploy
